server:
  port: 5050

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dbexample
    username: root
    password: root
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: create-drop